### ISSUE TITLE
Tests with other compilers

### ISSUE THREAD

**Issue by Algias** [RobLoach/raylib-cpp#42]
Currently  the CMakeLists.txt for the tests are not compatible with MSVC compiler options. It would be great to ensure testing is functional on Windows / other compilers if possible.

**Comment by RobLoach** [comment]
That would be great! The workflow is over at https://github.com/RobLoach/raylib-cpp/blob/master/.github/workflows/Tests.yml 

Would be pretty eay to add a test for Windows. I'll make a PR and we can see if it works.

**Comment by RobLoach** [comment]
The other thing we could do is refactor the tests so that they work in MSVC. Do you have a recommendation around doing that?

**Comment by RobLoach** [comment]
The problem is catch.hpp. It includes windows.h, which breaks compilation since winuser.h has a CloseWindow function that conflicts with raylib's function.

**Comment by Raelr** [comment]
Hey @RobLoach! 

Just jumping in because we've recently run into the same issue with building tests on Windows. In our case, we've pulled in Catch as our testing library and have run into similar errors. You can find our implementation in our [repository](https://github.com/CapsCollective/a-dark-discomfort/blob/main/.github/workflows/windows.yml). You can see the results of the test [here](https://github.com/CapsCollective/a-dark-discomfort/pull/15/checks?check_run_id=2869235246). 

This is a pretty important issue to us and we're happy to work together with you to solve it. In our case, the issue is related to the [Rectangle](https://github.com/RobLoach/raylib-cpp/blob/master/include/Rectangle.hpp#L12) class, which pulls in data from the `Rectangle` in the `raylib` C library. The core of the issue is that `raylib` has a `Rectangle` class that directly conflicts with a `Rectangle` definition in `windows.h`. We suspect that this might not be entirely solve-able unless the original definition is changed. 

One possible action we could take is to open up an issue with the Catch team to point out their inclusion of the entire `windows.h` library. Perhaps we could convince them to only include the parts they specifically need? This would likely resolve the build issues for windows entirely.

Let us know what you think or if you have any other ideas!

**Comment by RobLoach** [comment]
I've found warnings come from raymath as well. Are those flagged as errors in your compiler? For example....

```
 ./include/./raymath.h:1061:48: error: expected ')' before ';' token
     result.m14 = -((float)far + (float)near)/fn;
```

There isn't really anything wrong with the above line, but it's flagging it as an error.

**Comment by RobLoach** [comment]
Other thing we could consider is removing Catch.hpp entirely, and using plain 'ol `assert()`.

**Comment by RobLoach** [comment]
Removed catch.hpp.

**Comment by RobLoach** [comment]
This should be okay now, since it's using c's assert instead.

**Comment by RobLoach** [comment]
Would love your help on testing on Windows if you have the opportunity to.
